pub const ARROW_JOURNEY_SPEED: f32 = 200.;

pub const ARROW_JOURNEY_START_POSITION: f32 = -400.;

pub const ARROW_JOURNEY_END_POSITION: f32 = 200.;

pub const ARROW_CLICK_THRESHOLD: f32 = 20.;

pub const ARROW_JOURNEY_DISTANCE: f32 = ARROW_JOURNEY_END_POSITION - ARROW_JOURNEY_START_POSITION;